Add examples
InjectiveLabs/injective-sdk-ts-example pull request #1
Opened 2022-05-02 13:34 UTC by achilleas-kal

2022-05-02 13:57 UTC, bangjelkoski approved these changes

2022-05-02 18:52 UTC, bangjelkoski requested changes

2022-05-02 18:52 UTC, bangjelkoski commented on src/client/exchange/accounts_rpc/2_SubaccountBalance.ts
> +export const prettyPrint = (object: any): string => {
Please put it in `./src/utils/index.ts`

2022-05-04 12:14 UTC, bangjelkoski requested changes

2022-05-04 12:14 UTC, bangjelkoski commented on src/client/exchange/derivative_exchange_rpc/11_StreamTrades.ts
> +//   const executionSide = "maker";
These should be based on enums, so `ExecutionSide.Maker` and not hardcoded like this. Same goes for `direction` and `orderSide`

2022-05-04 12:15 UTC, achilleas-kal commented on src/client/exchange/derivative_exchange_rpc/11_StreamTrades.ts
> +//   const executionSide = "maker";
yeah I know already fixed for orderSide, need to fix a few other things for these functions and will change to enums.

2022-07-28 08:53 UTC, merged